name: Docker Image 만들고, EC2 배포
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # 도커 이미지에 env 파일 포함
      - name: Create .env file
        run: |
          touch .env
          echo REACT_APP_Server_IP ="${{ secrets.REACT_APP_SERVER_IP }}" >> .env

      # 내 도커허브 로그인
      - name: docker login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker 빌드 및 푸시
      - run: |
          docker build -t ${{secrets.DOCKER_REPO}}/diabet-app:${{github.sha}} .
          docker push ${{secrets.DOCKER_REPO}}/diabet-app:${{github.sha}}

      # 도커이미지 빌드하고 허브로 푸쉬
      - name: EC2에서 이미지 pull 후, 컨테이너 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker kill $(docker ps -qf expose=80) 2> /dev/null || echo 'No container running on port 80'
            docker kill $(docker ps -qf expose=3000) 2> /dev/null || echo 'No container running on port 3000'
            docker run -d -p 80:3000 ${{secrets.DOCKER_REPO}}/diabet-app:${{github.sha}}
